name: CI

on:
  push:
    branches:
      - feat/alexsantos

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PORT: 3000
      MONGODB_URL: "mongodb+srv://alexsantoswebdeveloper:Alphometa-7804@utmify.txarl.mongodb.net/?retryWrites=true&w=majority&appName=Utmify"
      EXCHANGE_RATE_API_URL: "https://v6.exchangerate-api.com/v6/e0cfaf3a14e1b2e1b320517e/latest/"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
